import "./globals.css";
import { DM_Sans } from '@next/font/google';

const dmSans = DM_Sans({
  subsets: ['latin'],  // Use 'latin' to support most western languages
  weight: ['400', '500', '700'],  // Select desired font weights
  display: 'swap',  // Optimize loading performance
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
